# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 's2g' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for s2g
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'SwiftyBeaver'

  target 's2gTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 's2gUITests' do
    # Pods for testing
  end

end
